### PR TITLE
Add GlyphBrush::drawn_rect_at

### PR DESCRIPTION
**Pull request by M-Adoo**
Export the rect position the glyph has drawn, if this glyph is currently present in the draw cache texture.

### CODE REVIEW

**Comment by alexheretic** [comment]
Thanks for the pr. Can you explain why you want this? This info should be used during vertex generation which is cached.

**Comment by M-Adoo** [comment]
Yes, I used it during vertex generation, but also want to query a glyph drawing rect after drawing, use to check if a glyph is layout in the bounds or do some hit test.

**Comment by alexheretic** [comment]
This is really a way of getting `pixel_bounds` for a single glyph then. But only if it's been queued & processed. This seems a bit niche but I'm not against having it, though we'll have to work on the naming.

I would use the glyph's layout bounds though, is there a reason the glyphs bounds aren't good enough for you? I.e what you get from `glyph_bounds` method but for one glyph. This works for any glyph and is fast, so should be preferable I would have thought.

```rust
// get the bounds of a single glyph
let sfont = self.fonts[font_id.0].as_scaled(glyph.scale);
let pos = glyph.position;
let lbound = Rect {
    min: point(
        pos.x - sfont.h_side_bearing(glyph.id),
        pos.y - sfont.ascent(),
    ),
    max: point(
        pos.x + sfont.h_advance(glyph.id),
        pos.y - sfont.descent(),
    ),
};
```

Maybe ab_glyph should have a method for this...

**Comment by M-Adoo** [comment]
Really nice for your example, it's  good for me.

**Comment by alexheretic** [comment]
I'll add a method to ab_glyph for this, as it's already used here and may be more generally helpful elsewhere: https://github.com/alexheretic/ab-glyph/pull/5

**Comment by M-Adoo** [comment]
Thanks your quick response.

**Comment by M-Adoo** [comment]
I found you have updated ab_glyph, but not export `glyph_bounds` in glyph brush. Or is there a way I don't know? @alexheretic

**Comment by alexheretic** [comment]
It's a method [`ab_glyph::Font::glyph_bounds`](https://docs.rs/ab_glyph/0.2.2/ab_glyph/trait.Font.html#method.glyph_bounds), glyph_brush re-exports all ab_glyph.

You may want to require ab_glyph `0.2.2` in your manifest. Otherwise nothing is stopping you that I can think of.

**Comment by M-Adoo** [comment]
> ab_glyph::Font::glyph_bounds

Font in `GlyphBrush` is not export, how can I query a `Font` from `FontId` ?

**Comment by alexheretic** [comment]
You can access the fonts your using in the brush with [GlyphCruncher::fonts](https://docs.rs/glyph_brush/0.7.0/glyph_brush/trait.GlyphCruncher.html#tymethod.fonts) which `GlyphBrush` implements. The fontid is the index, check the docs :)

**Comment by M-Adoo** [comment]
Thanks a lot.

**Pull request closed without merging**
