### PR TITLE
Implement a tagged glyph generator

### PR DESCRIPTION
**Pull request by BourgondAries**
This patch puts the generated vertices in a `Vec<Vec<_>>`, which is
useful because we want to be able to be able to distinguish vertices
from their respective text sections.

Why do this? Because when I render I do not query this library for every
frame. Instead, when a section is added, all `Section`s are `queue`d and
updated. Data from glyph-brush is then dumped into Vulkan buffers so
they can be redrawn efficiently.

Not only that, but having the text data in distinguishable buffer ranges
allows for various per-section and per-character transformations. For
instance, a single character of a section might be scaled or rotated or
translated differently from others. In addition to this, we can also
apply a transformation matrix to the entirety of the section's
associated UV data. I don't think it's proper for this library to
assume this role.

To add to this: I really would like to see an API where we don't need to
re-queue everything. My assumptions are that texels pretty much stay in
a DEVICE_LOCAL texture that is only updated when a very rare glyph
appears.

For games you'd likely just load every character that the font supports at
the beginning to avoid having to perform image updates while the process
is running. This is especially problematic in Vulkan as we'd need to do
the operation N times for N swapchain images, as we can't edit images
that are being used by frames that are in-flight. It's also fairly
expensive to keep streaming new texel data due to invalidation to the
GPU every so often.

### CODE REVIEW

**Comment by alexheretic** [comment]
It doesn't seem awful to return `Vec<Vec<V>>` but it isn't really the ideal _"give the the vertices for this section"_ api. The crate isn't really designed for this right now. Maybe just returning that as normal and providing a simple way to flatten it would work for both use cases?

> Because when I render I do not query this library for every
frame. Instead, when a section is added, all Sections are queued and
updated. Data from glyph-brush is then dumped into Vulkan buffers so
they can be redrawn efficiently.

Hmm it sounds like you've implemented what glyph-brush does with rusttype's gpu-cache. glyph-brush is designed to be called into every frame because it's very cheap to do so for re-draws. If you want to implement this yourself, why use glyph-brush at all?

> To add to this: I really would like to see an API where we don't need to
re-queue everything. My assumptions are that texels pretty much stay in
a DEVICE_LOCAL texture that is only updated when a very rare glyph
appears.

This is how the underlying rusttype gpu-cache works. So we'd need a different design there to change this.

> For games you'd likely just load every character that the font supports at
the beginning to avoid having to perform image updates while the process
is running. 

A single character of a single font can produce many distinct glyphs at different sub-pixel position and sizes. This is an important part of how rusttype draws good looking paragraphs. The dynamic texture management can work well for games, I think it's mostly suited for "screen text" rather than text in a 3d perspective though.

**Comment by BourgondAries** [comment]
>Hmm it sounds like you've implemented what glyph-brush does with rusttype's gpu-cache. glyph-brush is designed to be called into every frame because it's very cheap to do so for re-draws. If you want to implement this yourself, why use glyph-brush at all?

I've tried using it but couldn't figure it out exactly, it also seems to require `cache_queued` which - if I'm not mistaken - also clears some queue. Then there's also the requirement of copying your own `layout_paragraph` as from the example. This is something I'd like to avoid copying into my code as I'm not very knowledgeable on fonts.

**Comment by alexheretic** [comment]
>I've tried using it but couldn't figure it out exactly, it also seems to require cache_queued which - if I'm not mistaken - also clears some queue. Then there's also the requirement of copying your own layout_paragraph as from the example. This is something I'd like to avoid copying into my code as I'm not very knowledgeable on fonts.

The internal `cache_queued` method is called when you `queue` stuff. It runs the layout code that turns the section into `Vec<(PositionedGlyph<'font>, Color, FontId)>`. This is cached, so if this has been done on a previous frame it isn't re-done.

So generally you `queue` a bunch of sections in a frame, then call `process_queued` to produce vertex data. This method will check the "queue" state if it's the same as last frame it'll simply return `BrushAction::ReDraw`.

In this way the majority of the time, when sections are unchanged glyph-brush is just checking hashes saying "re-draw".

There is some cleanup in the `cleanup_frame` internal function, this is clearing out sections that were not used in the last frame avoiding unbound cache growth. So the lib is very much designed around a single `process_queued` call per frame and should be quite efficient if used this way.

**Comment by BourgondAries** [comment]
Thanks for the explanation. I think what want is just to explicitly "deallocate" and "allocate" sections, not having to enqueue them or iterate over them at all. That is - it is known when a section is no longer needed and rusttype/glyph brush doesn't need to be updated each frame about which sections are active. Is there a way to do in rusttype? Explicit layout compression control would also be nice, so we can assume UV values stay the same - and if we want - compress the store if it gets close to the device limits.

So while glyph_brush is intended to be called each frame with all active sections, my case simply allows for one to skip the re-enqueuement because we know when the section is deleted. At 100 sections it takes ~31 µs to process them. If this is done every frame (at 60 fps) we get about 1.86 ms being spent every second on just re-enqueuement alone. While it's not much, death by a thousand papercuts can add up, so if it can be avoided that would be ideal.

**Comment by alexheretic** [comment]
> Thanks for the explanation. I think what I want is to just explicitly "deallocate" and "allocate" sections, not having to enqueue them or iterate over them at all. That is - it is known when a section is no longer needed and rusttype/glyph brush doesn't need to be updated each frame about which sections are active. Is there a way to do in rusttype? Explicit layout compression control would also be nice, so we can assume UV values stay the same - and if we want - compress the store if it gets close to the device limits.

rusttype is flexible, but the gpu-cache module API isn't designed that way. It has a queue + process design that glyph-brush mirrors. I have a different design in mind where you "lease" your glyph requirements (and un-lease via drop) in the gpu texture cache instead of explicitly queuing every frame. Unfortunately, right now I don't have the free time to look into it.

> So while glyph_brush is intended to be called each frame with all active sections, my case simply allows for one to skip the re-enqueuement because we know when the section is deleted. At 100 sections it takes ~31 µs to process them. If this is done every frame (at 60 fps) we get about 1.86 ms being spent every second on just re-enqueuement alone. While it's not much, death by a thousand papercuts can add up, so if it can be avoided that would be ideal.

If you know nothing has changed since the last frame you can avoid queueing & processing. In general you'll need code to check nothing has changed in order to avoid glyph-brush's checks that nothing has changed. I'm surprised this is showing as a significant in your frametime. Of course your use-case will be different to mine.

Ultimately the queue+process design comes from the gpu texture-cache API and that foundation would need to be changed to change glyph-brush. If you want to use rusttype directly and write you're own texture caching logic you may still find `glyph_brush_layout` useful. Or maybe not. Glyph-brush wasn't meant to solve everyone's problems, just provide for others how I solved mine in Robo Instructus.

**Comment by alexheretic** [comment]
I forget my exact feelings on this PR, but it looks like we diverged a bit. I'll close for now as I don't think I'm fully on-board with the intention, please re-open with new info / corrections.

**Pull request closed without merging**
